#server:
#  port: 8080
spring:
  application:
    name: wfffff

  datasource.url: jdbc:h2:file:./camunda-h2-database

  cloud:
    consul:
      host: 10.0.0.50
      port: 8500

      #      port: 8500

      discovery:
        #        port: ${server.port}
        #    health-check-path: ${management.contextPath}/health
        #  healthCheckPath: ${management.server.servlet.context-path}/health
        # healthCheckPath: /health
        healthCheckInterval: 60s
        ipAddress: 10.0.0.51
        preferIpAddress: true
        #   port: ${server.port}
        #    health-check-path: ${management.contextPath}/health
        #      healthCheckPath: ${management.server.servlet.context-path}/health
management.endpoint.health.group.custom.show-components: always
management.endpoint.health.group.custom.show-details: always
grpc:
#  server:
#    port: 9898
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    role:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    user:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    company:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    message:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    employee:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    dictionary:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    collaboration:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    coalpit:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    delivery:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    logistics:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    buyer:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    position:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    verification:
      #address: 'static://10.0.0.50:6582'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
#    local-grpc-server:
#      address: 'static://127.0.0.1:9898'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#      negotiationType: plaintext

    reconciliation:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    qrcode:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    favorite:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext



camunda.bpm:
  admin-user:
    id: demo
    password: demo
    jobExecutorActivate: true

  #job-execution.enabled: false
  #job-execution.active: true

  reactor.reactor-listener-first-on-user-task: true
  eventing:
    execution: true
    history: true
    task: true